### ISSUE TITLE
agents是什么东西

### ISSUE THREAD

**Issue by zhaochuanyun** [hacktmz/goproducer#3]
干什么用的？可以不配吗

**Comment by hacktmz** [comment]
> 干什么用的？可以不配吗

可以。改成kafka集群就好了

**Comment by zhaochuanyun** [comment]
我的配置如下：
binlog_flush_ms = 2000  #2s刷新一次

[clusters]
agents = ["127.0.0.1:9092"]

[log]
log_path = "log/producer.log"
type = 2
highlighting = false
level = "info"

#定义订阅的mysql主库的连接信息
[[mysql]]
id = "1"
addr = "localhost:3306"
user = "xxx"
password = "xxx"
flavor = "mysql"
data_path = "./conf/master1.info"
nsname = "mysqlsync"
tablename = "orders"





"mysqlsync"是我要同步的库，"orders"是要同步的表。然后启动后，在orders表增删了几条数据：

API server listening at: 127.0.0.1:58163
rail start succ. %s 1
2019/06/21 11:25:29 warn conn 1 read failed
2019/06/21 11:25:29 warn conn 2 read failed
2019/06/21 11:25:29 warn conn 3 read failed
2019/06/21 11:25:29 error request: "32\nns:mysqlsync,tab:orders,proto:by\n5\nqpush\n9\nmysqlsync\n57\ndelete from mysqlsync.orders where order_id in (1321505);\n\n" failed
